FROM node:18

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap && yarn build

EXPOSE $SERVER_PORT

CMD [ "node", "./packages/server/dist/index.js" ]
