version: "3.9"

services:
    postgres:
      image: postgres:14
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data

    pgadmin:
      image: dpage/pgadmin4:6.19
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: secret
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "8080:80"
      volumes:
        - ./tmp/pgadmin-data:/var/lib/pgadmin
      depends_on:
        - postgres

networks:
  default:
    name: fancy_default
    external: true
