export const mockData = [
  {
    data: {
      game_id: 1,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 2,
      username: 'Player',
      avatar:
        '/0017fa8c-2b6f-4f70-9c94-11a70362be4c/c57d9e3d-33d2-41de-b529-9c52c55852c8_icons8-фламинго-96.png',
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 3,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 4,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 5,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 6,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 7,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 8,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 9,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 10,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 11,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 12,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 13,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 14,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 15,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 16,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 17,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 18,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 19,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 20,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 21,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 22,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 23,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 24,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 25,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 26,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 27,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 28,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 29,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 30,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 31,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 32,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 33,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 34,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
  {
    data: {
      game_id: 35,
      username: 'Player',
      avatar: undefined,
      score: 3,
      wins_2: 3,
      wins_4: 2,
      total_wins: 5,
    },
  },
];
