export const testForumData = [
  {
    number: 1,
    topic:
      'Стратегии в UNO (Подробный гайд с очень большим количеством слов вот)',
    total_messages: 100,
    author: 'Максимиллиан',
    last_message:
      'У меня получилось выиграть два раза подряд за время меньше У меня получилось выиграть два раза подряд за время меньше',
  },
  {
    number: 2,
    topic: 'Варианты правил UNO',
    total_messages: 51,
    author: 'Эля',
    last_message: 'Я иногда забываю нажать на кнопку очень раздажает(',
  },
  {
    number: 3,
    topic: 'Баги в игре',
    total_messages: 2,
    author: 'Элеонора',
    last_message: 'Чет всё зависло. Не дает ходить хотя мой ход.',
  },
  {
    number: 4,
    topic: 'Баги в игре',
    total_messages: 2,
    author: 'Элеонора',
    last_message: 'Чет всё зависло. Не дает ходить хотя мой ход.',
  },
  {
    number: 5,
    topic: 'Баги в игре',
    total_messages: 2,
    author: 'Элеонора',
    last_message: 'Чет всё зависло. Не дает ходить хотя мой ход.',
  },
  {
    number: 6,
    topic: 'Баги в игре',
    total_messages: 2,
    author: 'Элеонора',
    last_message: 'Чет всё зависло. Не дает ходить хотя мой ход.',
  },
  {
    number: 7,
    topic: 'Баги в игре',
    total_messages: 2,
    author: 'Элеонора',
    last_message: 'Чет всё зависло. Не дает ходить хотя мой ход.',
  },
  {
    number: 8,
    topic: 'Баги в игре',
    total_messages: 2,
    author: 'Элеонора',
    last_message: 'Чет всё зависло.',
  },
  {
    number: 9,
    topic: 'Баги в игре',
    total_messages: 2,
    author: 'Элеонора',
    last_message: 'Чет всё зависло. Не дает ходить хотя мой ход.',
  },
  {
    number: 10,
    topic: 'Баги в игре',
    total_messages: 2,
    author: 'Элеонора',
    last_message: 'Чет всё зависло. Не дает ходить хотя мой ход.',
  },
  {
    number: 11,
    topic: 'Баги в игре',
    total_messages: 2,
    author: 'Элеонора',
    last_message: 'Чет всё зависло. Не дает ходить хотя мой ход.',
  },
  {
    number: 12,
    topic: 'Баги в игре',
    total_messages: 2,
    author: 'Элеонора',
    last_message: 'Чет всё зависло. Не дает ходить хотя мой ход.',
  },
];
